api = "0.2"

[buildpack]
  id = "com.anynines.buildpacks.rvm"
  name = "RVM Buildpack in Go"

[metadata]
  include-files = ["bin/build","bin/detect","buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [metadata.configuration]
    uri = "https://get.rvm.io"
    default_rvm_version = "1.29.10"
    default_ruby_version = "2.7.1"
    default_require_node = false
    default_node_version = "12.*"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
